### ISSUE TITLE
deadant2Edits: Something's missing in remember()

### ISSUE THREAD

**Issue by rahlk** [ai-se/Rahul#13]
The [remember function](https://github.com/ai-se/Rahul/blob/master/deadant2Edits.py#L313) refuses to work. Here's what I get:

```
TypeError: unsupported operand type(s) for +=: 'instance' and 'list'
```

**Comment by rahlk** [comment]
Error in `m+=new`, the model class had no **iadd**. Also, I think `self.pop[ new[0].id ] = new;` does the job anyway.

**Comment by timm** [comment]
which file/function is this?

**Comment by rahlk** [comment]
It's here
https://github.com/ai-se/Rahul/blob/master/deadant2Edits.py#L313

**Comment by rahlk** [comment]
`m+=new` was replaced by `m.tell(new)`
